_wandb:
    value:
        cli_version: 0.21.1
        e:
            jzog8aqfpc5vso3zeh7s9drtgdru41p5:
                codePath: train_resnet_autoencoder.py
                codePathLocal: train_resnet_autoencoder.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "187849678848"
                        used: "23821119488"
                email: lyj6626076@gmail.com
                executable: /home/lyj/anaconda3/envs/data_ans/bin/python
                git:
                    commit: 6eb3b2ca6c4f19826daac66b12c6534fe37dc667
                    remote: git@github.com:pb-lyj/Tactile_blind_manipulation.git
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-db685074-6ffe-af78-96e2-ea0b477c354a
                host: pb
                memory:
                    total: "33454800896"
                os: Linux-6.14.0-29-generic-x86_64-with-glibc2.39
                program: /home/lyj/Program_python/Probefahrt/train_resnet_autoencoder.py
                python: CPython 3.11.11
                root: ae_checkpoints/resnet18_autoencoder_20250929_161034
                startedAt: "2025-09-29T08:10:34.528157Z"
                writerId: jzog8aqfpc5vso3zeh7s9drtgdru41p5
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 3
                - 13
                - 15
                - 16
                - 61
            "4": 3.11.11
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
data:
    value:
        categories:
            - cir_lar
            - cir_med
            - cir_sma
            - rect_lar
            - rect_med
            - rect_sma
            - tri_lar
            - tri_med
            - tri_sma
        data_root: data25.7_aligned
        normalize_method: zscore
        start_frame: 0
loss:
    value:
        force_lambda: 1e-05
        l2_lambda: 0.001
        moment_lambda: 5e-07
        use_resultant_loss: false
model:
    value:
        freeze_bn: false
        in_channels: 3
        keep_stem: true
        latent_dim: 128
        pretrained: true
        rescale_to_01: false
        use_preprocess: true
output:
    value:
        output_dir: ae_checkpoints
training:
    value:
        batch_size: 32
        epochs: 100
        eval_every: 1
        lr: 0.0001
        weight_decay: 0.0001
wandb:
    value:
        name: resnet18_ae_run
        project: tactile-latent-autoencoder
