_wandb:
    value:
        cli_version: 0.21.1
        e:
            2z0yo69ua4ljhw2y2wn2d6ms698zhx8h:
                codePath: train_cnn_autoencoder.py
                codePathLocal: train_cnn_autoencoder.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "187849678848"
                        used: "22695636992"
                email: lyj6626076@gmail.com
                executable: /home/lyj/anaconda3/envs/data_ans/bin/python
                git:
                    commit: 9a8a5a12b7549fa2beb4dc0166e71bbc5928f2c0
                    remote: git@github.com:pb-lyj/Tactile_blind_manipulation.git
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-db685074-6ffe-af78-96e2-ea0b477c354a
                host: pb
                memory:
                    total: "33454804992"
                os: Linux-6.14.0-29-generic-x86_64-with-glibc2.39
                program: /home/lyj/Program_python/Probefahrt/train_cnn_autoencoder.py
                python: CPython 3.11.11
                root: ae_checkpoints/cnn_autoencoder_20250909_085037
                startedAt: "2025-09-09T00:50:37.338929Z"
                writerId: 2z0yo69ua4ljhw2y2wn2d6ms698zhx8h
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 3
                - 13
                - 15
                - 16
                - 61
            "4": 3.11.11
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
data:
    value:
        categories:
            - cir_lar
            - cir_med
            - cir_sma
            - rect_lar
            - rect_med
            - rect_sma
            - tri_lar
            - tri_med
            - tri_sma
        data_root: data25.7_aligned
        normalize_method: zscore
        start_frame: 0
loss:
    value:
        force_lambda: 0.1
        l2_lambda: 0.001
        moment_lambda: 0.05
        use_resultant_loss: false
model:
    value:
        in_channels: 3
        latent_dim: 128
output:
    value:
        output_dir: ae_checkpoints
training:
    value:
        batch_size: 32
        epochs: 100
        eval_every: 2
        lr: 0.0001
        weight_decay: 0.0001
wandb:
    value:
        name: cnn_ae_base_run
        project: tactile-latent-autoencoder
